#!/bin/bash

# Clean the environment
reset
if test -f "Makefile"; then
    make clean && rm .qmake.stash OpenRGB Makefile
fi

# Make OpenRGB
git submodule update --init --recursive
qmake OpenRGB.pro
make -j24

# Test before moving
 ./openrgb

echo "Does it work?"
select ynq in "yes" "no" "quit"; do
    case $ynq in
	yes ) mv openrgb OpenRGB && cp -f OpenRGB ~/bin;break;;
	no ) echo "UhOh!" && exit;break;;
	quit ) echo "Nothing done. Good Bye!";exit;;
esac;
done


